import styles from "../styles/about.module.css";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRight } from "@fortawesome/free-solid-svg-icons";
import { faArrowDown } from "@fortawesome/free-solid-svg-icons";
import { faGithub } from "@fortawesome/free-brands-svg-icons";
import { faLinkedin } from "@fortawesome/free-brands-svg-icons";
import { faEnvelope } from "@fortawesome/free-solid-svg-icons";
import useSWR from "swr";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Marcos Freire Portfolio",
    template: "%s Codevolution",
  },
  description: "Generated by Next.js",
};

const UsersPage = () => {
  return (
    <div className={styles.intro}>
      <div className={styles.logo}>
        <Link href="/">
          <h1 className={styles.aboutTitle}>MF</h1>
        </Link>
      </div>
      {/* <div className="about-title aligned">
      <h1>Biography</h1>
      <div className="links aligned">
        <a href="https://github.com/mfreire1996" target='_blank'>
      <FontAwesomeIcon icon={faGithub} className='icon' />
        </a>
        <a href="https://www.linkedin.com/in/marcos-freire/" target='_blank'>
        <FontAwesomeIcon icon={faLinkedin} className='icon' />
        </a>
        <a href="mailto:mfreire1996@gmail.com">
        <FontAwesomeIcon icon={faEnvelope} className='icon'/>
          </a>
      </div>
      </div> */}

      <div className={styles.introContainer}>
        <div className={styles.introBio}>
          <hr className={styles.hr} />
          <p>
            Hi there, I'm Marcos, a New York City-based Web Developer. With my 5
            years of diverse experience, I've worked on a variety of roles such
            as design, development, logo designing and much more. I have a
            passion for crafting diverse websites and I strive to leverage
            technology to enhance businesses and streamline daily tasks,
            recognizing its pivotal role in modern society.
          </p>
        </div>

        <div className={styles.introText}>
          <p>
            My journey in coding commenced during my time at DeVry University,
            where I wrote my inaugural line of Python code. Since that moment,
            my passion for coding has only deepened. I continued to refine my
            skills by enrolling in the New York Code + Design Academy,
            culminating in my graduation from Laguardia College.
          </p>
          <br />
          <p>
            Over the past few years, I have had the privilege of collaborating
            on numerous projects and partnering with talented developers from
            diverse backgrounds. Through these experiences, I have cultivated
            valuable skills in effective communication, earned the trust of
            clients, and gained insights into the dynamic world of freelance
            development.
          </p>
          <br />
          <p>
            I am committed to continuous improvement in all aspects of my work,
            embracing challenges as opportunities for growth. My greatest
            strength lies in my eagerness to learn and my ability to adapt to
            any environment. I thrive on pushing the boundaries of what's
            possible, constantly seeking new experiences, and refining my
            skills.
          </p>
          <br />
          <p>
            I am currently enhancing my skills by learning new programming
            languages and refreshing my knowledge of existing ones. I regularly
            attend coding networking events, so please feel free to connect with
            me!
          </p>
        </div>
      </div>

      <div className={styles.resume}>
        <a href="mailto:mfreire1996@gmail.com" target="_blank">
          <h3 className={styles.hover}>mfreire1996@gmail.com</h3>
        </a>
        <a href="/Marcos-Resume.docx" target="_blank">
          <h3 className={styles.resumeTitle}>Resume</h3>
        </a>
        <a href="https://www.linkedin.com/in/marcos-freire/" target="_blank">
          <h3 className={styles.hover}>Linkedin</h3>
        </a>
        <a href="https://github.com/mfreire1996" target="_blank">
          <h3 className={styles.hover}>Github</h3>
        </a>
      </div>

      <div className={styles.marcos}>
        <img src="/me.jpg" alt="Marcos Freire" className={styles.marcosImg} />
      </div>
    </div>
  );
};

export default UsersPage;
