import styles from "../../styles/styles.module.css";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import React, { useEffect } from "react";
import Script from "next/script";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faArrowRight } from "@fortawesome/free-solid-svg-icons";
import "@fortawesome/fontawesome-svg-core/styles.css";
import useSWR from "swr";
// import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Marcos Freire Portfolio",
    template: "%s Codevolution",
  },
  description: "Generated by Next.js",
};

const NewUsers = () => {
  return (
    <main>
      <Head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
          integrity="..."
          crossOrigin="anonymous"
        />
      </Head>
      <div className={styles.body}>
        <div className={styles.logo}>
          <Link href="/">
            <h1>MF</h1>
          </Link>
        </div>

        <div className={styles.container}>
          <div className={styles.card__container}>
            <article className={styles.card__article}>
              <img
                src="/brotherhood.jpg"
                alt="Brotherhood Boxing"
                className={styles.card__img}
              />

              <div className={styles.card__data}>
                <span className={styles.card__description}>Boxing Gym</span>
                <h2 className={styles.card__title}>Brotherhood Boxing</h2>
                <a
                  href="https://brotherhoodboxing.org/"
                  className={styles.card__button}
                  target="_blank"
                >
                  See site
                </a>
              </div>
            </article>

            <article className={styles.card__article}>
              <img
                src="/loopstudio.png"
                alt="Loopstudio"
                className={styles.card__img}
              />

              <div className={styles.card__data}>
                <span className={styles.card__description}>
                  Inside Loopstudio
                </span>
                <h2 className={styles.card__title}>Loopstudio</h2>
                <a
                  href="https://mfreire1996.github.io/loopstudio/"
                  className={styles.card__button}
                  target="_blank"
                >
                  See site
                </a>
              </div>
            </article>

            <article className={styles.card__article}>
              <img
                src="/calculator.png"
                alt="Calculator"
                className={styles.card__img}
              />

              <div className={styles.card__data}>
                <span className={styles.card__description}>A calculator</span>
                <h2 className={styles.card__title}>Calculator</h2>
                <a
                  href="https://mfreire1996.github.io/calculator/"
                  className={styles.card__button}
                  target="_blank"
                >
                  See site
                </a>
              </div>
            </article>

            {/* comment */}

            <article className={styles.card__article}>
              <img
                src="/marianita.png"
                alt="Marianita"
                className={`${styles.card__img} ${styles.testImg}`}
              />

              <div className={styles.card__data}>
                <span className={styles.card__description}>
                  A real estate agent
                </span>
                <h2 className={styles.card__title}>Marianita's Real Estate</h2>
                <a
                  href="https://mfreire1996.github.io/mariantcord2023/"
                  className={styles.card__button}
                  target="_blank"
                >
                  See site
                </a>
              </div>
            </article>

            <article className={styles.card__article}>
              <img
                src="/newsletter.png"
                alt="Newsletter"
                className={styles.card__img}
              />

              <div className={styles.card__data}>
                <span className={styles.card__description}>A newsletter</span>
                <h2 className={styles.card__title}>Newsletter</h2>
                <a
                  href="https://mfreire1996.github.io/newsletter/"
                  className={styles.card__button}
                  target="_blank"
                >
                  See site
                </a>
              </div>
            </article>

            <article className={styles.card__article}>
              <img
                src="/ridgewood.png"
                alt="Calculator"
                className={`${styles.card__img} ${styles.testImg}`}
              />

              <div className={styles.card__data}>
                <span className={styles.card__description}>A barbershop</span>
                <h2 className={styles.card__title}>Barbershop</h2>
                <a
                  href="https://mfreire1996.github.io/ridgewood-haircuts/"
                  className={styles.card__button}
                  target="_blank"
                >
                  See site
                </a>
              </div>
            </article>
          </div>
        </div>
      </div>
    </main>
  );
};

export default NewUsers;
